import type { Metadata } from "next";
import "../global.css";
import { Inter } from "next/font/google";
import Header from "../(home)/components/Header";
import React from "react";

const inter = Inter({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function MainLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return <div className={`${inter.className}`}>{children}</div>;
}
